version: '3.9'
services:

    gitlab_runner:
        image: gitlab-runner:latest
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: gitlab_runner
        volumes:
          - /srv/gitlab-runner/config:/etc/gitlab-runner
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - smtplink

networks:
    smtplink:
        driver: bridge
        external: true